### ISSUE TITLE
Lister les ressources existantes sur UNIL.CH/HIST

### ISSUE THREAD

**Issue by grandjeanmartin** [LausanneCitationStyle/support#12]
Des exemples de bibliographies, consignes pour des séminaires, bibliographies thématiques de référence, conseils pour l'organisation et la recherche biblio, etc. parsèment les pages du site de la Section d'histoire. 
Les lister permettrait d'évaluer leur pertinence puis susciter une discussion avec nos collègues et éventuellement regrouper ce qui peut l'être (ou, à minima, créer des liens depuis une page dédiée).

**Comment by TaniaRochat** [comment]
[Liste des ressources existantes sur unil.docx](https://github.com/LausanneCitationStyle/support/files/4113626/Liste.des.ressources.existantes.sur.unil.docx)

En lien, un document listant tous les exemples de bibliographies, consignes pour des séminaires, bibliographies thématiques de références, conseils pour l'organisation et la recherche biblio, portails de recherche bibliographique, bases de données, bibliothèques, etc.

**Comment by grandjeanmartin** [comment]
Idée abandonnée. Ce n'est pas le lieu.
