### ISSUE TITLE
Page sur la recherche bibliographique

### ISSUE THREAD

**Issue by grandjeanmartin** [LausanneCitationStyle/support#14]
Partiellement redondante avec des contenus spécifiques mais permettrait de résumer les outils à disposition

**Comment by grandjeanmartin** [comment]
Pour mémoire, mini-liste produite pour les étudiants du MA EPFL:
Catalogues/moteurs de recherche:

Renouvaud: https://www.bcu-lausanne.ch/renouvaud/ (catalogue de la Bibliothèque cantonale et universitaire, indexe aussi des publications en ligne hors catalogue lausannois)
Isidore: https://isidore.science (moteur de recherche qui indexe les dépôts de revues et autres)
Google Scholar: https://scholar.google.com (index de publications avec profils de chercheurs)
Dépôts:

Cairn: https://www.cairn.info (revues en ligne)
OpenEdition: https://search.openedition.org/ (revues et livres en ligne)
Persée: https://www.persee.fr (revues numérisées)
HAL: https://hal.archives-ouvertes.fr (dépôt de publications francophones)
Erudit: https://www.erudit.org/fr/ (revues en ligne/Canada)
JSTOR: https://www.jstor.org (revues et livres en ligne)
E-Periodica: https://www.e-periodica.ch (revues et magazines suisses)

**Comment by TaniaRochat** [comment]
"Devenir historien·ne: Méthodologie de la recherche et historiographie" (https://devhist.hypotheses.org/)- Pas de billet sur Zotero, mais pourrait être un outil utile. Tout comme la "boîte à outil des historien·ne·s" (http://www.boiteaoutils.info/a-propos/)

**Comment by grandjeanmartin** [comment]
Idée abandonnée. Pourrait être recyclée en module vidéo de C&P.
