### ISSUE TITLE
Inventaire

### ISSUE THREAD

**Issue by grandjeanmartin** [LausanneCitationStyle/support#3]
Faire l'inventaire des tutoriels Zotero et, plus largement, des ressources potentiellement utiles (plugins, moyens d'hébergement des données, billets de blogs, retours d'expériences, etc.).

**Comment by grandjeanmartin** [comment]
-> https://www.biusante.parisdescartes.fr/ressources/pdf/zotero-tutoriel-biusante.pdf

**Comment by grandjeanmartin** [comment]
Voir aussi http://www.compas.infoclio.ch/fr/compas/1-6-1-zotero/72

**Comment by TaniaRochat** [comment]
Tutoriel YouTube de 2013, réalisé par l'URFIST Méditerranée, https://www.youtube.com/playlist?list=PLnROkFh2gxtSo64-B8JbmMjaezmWlRAVi

**Comment by TaniaRochat** [comment]
Blog Zotero francophone https://zotero.hypotheses.org/

**Comment by TaniaRochat** [comment]
Tutoriel créé par l'UdeM (Université de Montréal) qui comprend plusieurs renvois vers tutoriels YouTube https://bib.umontreal.ca/citer/logiciels-bibliographiques/zotero/installer

Et guide PDF (UdeM)
[Zotero_feuillederouteUdeM.pdf](https://github.com/LausanneCitationStyle/support/files/4142474/Zotero_feuillederouteUdeM.pdf)

Et guide d'installation et configuration pour Windows et Mac (UdeM)
https://bib.umontreal.ca/public/bib/soutien-informatique/ZOT1-installation-zotero.pdf

**Comment by TaniaRochat** [comment]
Tutoriel YouTube, apprendre à utiliser Zotero en 30min (anglais) https://www.youtube.com/watch?v=BQL_7C-YqBk

**Comment by TaniaRochat** [comment]
Tutoriel Zotero en 10 min (anglais) https://www.youtube.com/watch?v=Hm0TboOcAuM

**Comment by TaniaRochat** [comment]
Tutoriel Zotero du réseau d'université du Québec (dans l'environnement Windows avec Microsoft Office)
https://carrefour.uquebec.ca/zotero

**Comment by TaniaRochat** [comment]
Retour d'utilisation de Zotero, Blog d'une enseignante et chercheuse en linguistique
https://icietla.hypotheses.org/70

**Comment by TaniaRochat** [comment]
Billet sur l'utilisation de ZotLog par Pierre Martinolli, bibliothécaire à l'université de Montréal
https://tribuneci.wordpress.com/2016/10/11/zotlog-structurer-son-parcours-de-recherche-avec-zotero/

**Comment by TaniaRochat** [comment]
La boîte à outil des historien.ne.s
http://www.boiteaoutils.info/category/tutoriels/zotero/

**Comment by TaniaRochat** [comment]
Tutoriel Youtube sur le stockage de données à l'aide d'un "back-up" en ligne (anglais)
https://www.youtube.com/watch?v=5UV6Ce3evUY

**Comment by TaniaRochat** [comment]
Tutoriel, université de Laval (PDF)
https://www.bibl.ulaval.ca/fichiers_site/aide_recherche/zotero/guide-zotero.pdf

**Comment by TaniaRochat** [comment]
Le blog zotero
https://www.zotero.org/blog/

**Comment by TaniaRochat** [comment]
Anystyle.io
https://anystyle.io/

+ tutoriel (UdeM)
https://www.youtube.com/watch?v=VnKcsRFaM68

**Comment by TaniaRochat** [comment]
Plugin Zotfile

**Comment by TaniaRochat** [comment]
Plugin Zutilo
